module.exports = {
	REQUEST_TYPES : 1,
  RECEIVE_TYPES : 2,
  REQUEST_BRANDS: 3,
  RECEIVE_BRANDS: 4,
	REQUEST_TOPS_PRODUCT : 5,
	RECEIVE_TOPS_PRODUCT : 6,
	REQUEST_DETAIL_CAR : 7,
  RECEIVE_DETAIL_CAR : 8,
  REQUEST_SAME_TYPE_CARS : 9,
  RECEIVE_SAME_TYPE_CARS : 10,
  REQUEST_SAME_BRAND_CARS : 11,
  RECEIVE_SAME_BRAND_CARS : 12,
  REQUEST_GALLERY_CAR: 13,
  RECEIVE_GALLERY_CAR: 14
}
