module.exports = {
	REQUEST_MENU : 1,
	RECEIVE_MENU : 2,
	REQUEST_TOPS_PRODUCT : 3,
	RECEIVE_TOPS_PRODUCT : 4,
	REQUEST_DETAIL_CAR : 5,
  RECEIVE_DETAIL_CAR : 6,
  REQUEST_SAME_TYPE_CARS : 7,
  RECEIVE_SAME_TYPE_CARS : 8,
  REQUEST_SAME_BRAND_CARS : 9,
  RECEIVE_SAME_BRAND_CARS : 10,
  REQUEST_GALLERY_CAR: 11,
  RECEIVE_GALLERY_CAR: 12
}
